/// <reference types="next" />
/// <reference types="next/image-types/global" />

// Lets `tsc --noEmit` understand static image imports outside `next build`
// (next-env.d.ts is generated by Next and not committed).
